name: Agent-Provisioning

on:
  push:
    branches:
      - main
    paths:
      - 'apps/agent-provisioning/**'

jobs:
  build-and-push:
    name: Push Docker image to GitHub
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          echo "Building Docker image for agent-provisioning ..."
          docker build -t $IMAGE_NAME -f Dockerfiles/Dockerfile.agent-provisioning .

          echo "Pushing Docker image to GitHub Container Registry..."
          docker push $IMAGE_NAME
